AWSTemplateFormatVersion: "2010-09-09"
Description: s3-bucket-task; input and output files

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      BucketName: "S3Bucket"

  LoggingBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Bucket task with logging configuration and versioning
